### PR TITLE
Migrate away from prebuilt kernel, instead use Sonys msm8974 unified kernel

### PR DESCRIPTION
**Pull request by locusf**
Signed-off-by: Aleksi Suomalainen <suomalainen.aleksi@gmail.com>

### CODE REVIEW

**Comment by chirayudesai** [comment]
This could rather be moved to device-sony-rhine, using $(TARGET_DEVICE) wherever needed.

And could be done in Android.mk too, no need to resurrect a long obsolete AndroidBoard.mk :)

**Comment by chirayudesai** [comment]
And another thing, this is more of "Allowing building kernel inline" rather than migrating away from using a prebuilt kernel at all, so the commit message should be updated to reflect that.

**Comment by locusf** [comment]
Ok will fix tomorrow evening.

**Comment by chirayudesai** [comment]
Done already, https://github.com/sonyxperiadev/kernel/pull/148

Now for each board (rhine shinano yukon), we just need to set TARGET_KERNEL_CONFIG and TARGET_KERNEL_SOURCE

**Comment by jerpelea** [comment]
the other solution is clean

**Pull request closed without merging**
